#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:nil arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: README
#+date: <2023-04-27 Thu>
#+author: Yang Huang
#+email: huangyang@localhost.localdomain
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.5.5)
#+cite_export:

* Purpose
Calculate two-body entropy from pair correlation function.

* Dependency
GSL - GNU Scientific Library is required. In general, it is installed
by default in Linux operating systems. Or you can refer to [[https://www.gnu.org/software/gsl/][GSL
website]].

* Compilation
Type "make" and it will generate a "pdf2s2_v2" binary.

* Usage
"pdf2s2_v2 -x XDATCAR" for calculation or "pdf2s2_v2 -h" for help page.

** Input files
1) Mass
   This file contains three rows:
   - type of species.
   - atomic numbers.
   - atomic masses [a.u.] in atomic units.

2) Trun
   This file contains in value which is the temperature of MD simulation.

3) XDATCAR
   Standard output of VASP runs.
   
4) pdf files
   Pair distribution functions. You can generate those using "pdfxdat"
   command.
   
** Output files
1) pdf.??.s2
   Two-body entropy as a function of integral distance of each kind of
   pair in a form of
   | R [A] | S2(fluct) [kB] | S2(info) [kB] | S2(tot) [kB] |
   
2) tot.s2
   Total two-body entropy as a function of integral distance  a form of
   | R [A] | S2(fluct) [kB] | S2(info) [kB] | S2(tot) [kB] |
